### ISSUE TITLE
[Error] Build using Ubuntu

### ISSUE THREAD

**Issue by vonsofh** [KevinAdhaikal/AplikasiKasir#5]
I got this bug when clone and try to build using `build.sh`
```
src/CashierFunction/tambahBarang.c: In function ‘tambahBarang’:
src/CashierFunction/tambahBarang.c:42:44: warning: too many arguments for format [-Wformat-extra-args]
   42 |     if (!barcodeBarang[0])sprintf(strTemp, "SELECT lower(nama) FROM daftarBarang WHERE lower(nama) = lower('%s')", namaBarang, barcodeBarang);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by KevinAdhaikal** [comment]
> I got this bug when clone and try to build using `build.sh`
> 
> ```
> src/CashierFunction/tambahBarang.c: In function ‘tambahBarang’:
> src/CashierFunction/tambahBarang.c:42:44: warning: too many arguments for format [-Wformat-extra-args]
>    42 |     if (!barcodeBarang[0])sprintf(strTemp, "SELECT lower(nama) FROM daftarBarang WHERE lower(nama) = lower('%s')", namaBarang, barcodeBarang);
>       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

thanks for remind me, and i just fix it
