### ISSUE TITLE
[BUG] Some function not work as we want

### ISSUE THREAD

**Issue by vonsofh** [KevinAdhaikal/AplikasiKasir#6]
I found bug when try to scan/purchase item from menu "Kasir", the quantity of the item can be inputted more than the stock, example:
- Aqua 350ml (Stock: 5)
- Able to scan more than 5 times and still recorded in the system
- Should check when tried to scan more than stock limit

The second, when you try to click action button "Refresh" at "Barang Kosong", it will append the row again and again instead of refreshing the table

**Comment by KevinAdhaikal** [comment]
> I found bug when try to scan/purchase item from menu "Kasir", the quantity of the item can be inputted more than the stock, example:
> 
>     * Aqua 350ml (Stock: 5)
> 
>     * Able to scan more than 5 times and still recorded in the system
> 
>     * Should check when tried to scan more than stock limit
> 
> 
> The second, when you try to click action button "Refresh" at "Barang Kosong", it will append the row again and again instead of refreshing the table

thanks for reporting the bug, and yeah, i didnt make the check stock limit, and maybe, i will make that stock limit

**Comment by KevinAdhaikal** [comment]
kepencet awkowakowa, btw, ntar gw update untuk stock limit nya 👍
